### ISSUE TITLE
Share It MVP

### ISSUE THREAD

**Issue by PrismaPhonic** [libellis/share-it#1]
This describes steps for the initial MVP of Share It (In progress name, may change)

- [x] Create domain models. Find the minimal subset of data that will be returned from Soundcloud API that we will store for User and Song. Playlist and Waitlist are both concepts unrelated to soundcloud API responses.
  - [x] User domain model (Issue #2, PR #2 )
  - [x] Song domain model (Issue #3, PR #3)
  - [x] Playlist domain model (Issue #4, PR #10)
  - [x] Waitlist domain model (Issue #9, PR #11)
  - [x] Chatroom domain model (Issue #12, PR #14)
- [ ] Integration with Soundcloud API for the purpose of logging in - use SC for oauth.
- [ ] A basic chatroom with the concept of a "moderator" that has admin privileges over the room.
- [ ] A way for all users of a chat room to stream a single elected song. We also likely need a process for determining when a song is "done". Do we have a consensus process where all participants let us know when they are done listening (automatic), or simply derive it off of some global time with a buffer?
- [ ] Play button given to "moderator". Songs should automatically pause when done so as to wait for chatroom members to give feedback.
- [ ] Ability for users to save playlists they can come back to when they login again. This means we need to hold our own internal state. I think a simple key-value store here will be just fine. We could maybe try out [sled](http://sled.rs/)?

If I'm forgetting chunkable goals please edit and add them to the list!
